# Decrease maximum count of allowed unauthenticated connections
MaxStartups 10:30:30
# SSH access for root user only available with keys
PermitRootLogin prohibit-password
Match User root
    PasswordAuthentication no
    PubkeyAuthentication    yes
